<?php


function specials_menu() {
	
	$items = array();
	$items['specials'] = array(
			'title' => "Church Blurbs",
			'page callback' => 'specials_display',
			'access callback' => TRUE,
			'type' => MENU_NORMAL_ITEM,
		);

	return $items;
}

function specials_display() {
	return '
		<ul>
			<li>Saint Nicholas</li>
			<li>Olivet Presbyterian Church</li>
			<li>First Presbyterian Church Kensington</li>
		</ul>
	';
}